#!/usr/bin/env python3
"""Poke Labs Daily Morning Briefing."""
import json, os, urllib.request, subprocess
from datetime import datetime, timezone

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

def check(url, timeout=10):
    try:
        r = urllib.request.urlopen(urllib.request.Request(url, method="GET"), timeout=timeout)
        return "🟢 UP", str(r.status)
    except Exception as e:
        return "🔴 DOWN", str(e)[:50]

def gh(path):
    try:
        req = urllib.request.Request(f"https://api.github.com/{path}",
            headers={"Accept":"application/vnd.github.v3+json","User-Agent":"PokeLabs"})
        return json.loads(urllib.request.urlopen(req, timeout=10).read())
    except: return []

def generate():
    now = datetime.now(timezone.utc)
    
    # Service checks
    service_lines = []
    for name, url in [("Poke Labs", "https://pokelabs.org"), ("Council", "https://council.pokelabs.org")]:
        status, detail = check(url)
        service_lines.append(f"  {status} {name} ({detail})")
    
    # GitHub
    repos = gh("users/pokelabshq/repos?sort=updated&per_page=5")
    issues = sum(len(gh(f"repos/pokelabshq/{r}/issues?state=open&per_page=100")) for r in ["council","poke","services"])
    
    repo_lines = []
    for r in repos[:5]:
        repo_lines.append(f"  📦 {r['name']} — ⭐{r['stargazers_count']} · {r.get('language','?')} · {r['updated_at'][:10]}")
    
    commits = []
    for r in ["council","services"]:
        for c in gh(f"repos/pokelabshq/{r}/commits?per_page=3"):
            commits.append(f"  🔨 {r}: {c['commit']['message'].split(chr(10))[0][:60]} ({c['commit']['author']['date'][:10]})")
    
    return f"""☀️ *Poke Labs — Daily Briefing*
📅 {now.strftime('%A, %B %d, %Y')}

*🌐 Services*
{chr(10).join(service_lines)}

*📊 GitHub*
  🔓 {issues} open issues
{chr(10).join(repo_lines)}

*🔨 Recent Commits*
{chr(10).join(commits[:6])}

_Generated by Poke 🦾_"""

def send(msg):
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        print("Telegram not configured. Message:"); print(msg); return
    try:
        data = json.dumps({"chat_id":TELEGRAM_CHAT_ID,"text":msg,"parse_mode":"Markdown"}).encode()
        req = urllib.request.Request(f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage", data=data, headers={"Content-Type":"application/json"})
        r = json.loads(urllib.request.urlopen(req, timeout=10).read())
        print("✅ Sent!" if r.get("ok") else f"❌ {r}")
    except Exception as e: print(f"❌ {e}")

if __name__ == "__main__":
    b = generate(); print(b); print("---"); send(b)
