#!/usr/bin/env python3
"""Daily Digest Generator — scans all pokelabshq GitHub repos.

Usage:
  python3 digest.py                    # Print to stdout
  python3 digest.py --output file.txt  # Write to file
  python3 digest.py --json             # Output as JSON
"""
import subprocess, json, sys, os
from datetime import datetime, timedelta

ORG = "pokelabshq"
TODAY = datetime.utcnow().strftime("%Y-%m-%d")
NOW = datetime.utcnow()

def run(cmd):
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
        return r.stdout.strip()
    except:
        return ""

def get_repos():
    out = run(f"gh api users/{ORG}/repos?per_page=100 --jq '.[].full_name'")
    return [x for x in out.split('\n') if x]

def get_stale_issues(repo, days=30):
    cutoff = (NOW - timedelta(days=days)).strftime("%Y-%m-%d")
    out = run(f'gh issue list -R {repo} --state open --search "created:<{cutoff}" --limit 20 --json number,title,createdAt')
    try: return json.loads(out)
    except: return []

def get_stale_prs(repo, days=7):
    cutoff = (NOW - timedelta(days=days)).strftime("%Y-%m-%d")
    out = run(f'gh pr list -R {repo} --state open --search "created:<{cutoff}" --limit 20 --json number,title,createdAt,reviewDecision')
    try: return json.loads(out)
    except: return []

def get_ci_status(repo):
    out = run(f'gh api repos/{repo}/commits/main/status --jq ".state" 2>/dev/null')
    return out or "unknown"

def get_recent_issues(repo, days=7):
    cutoff = (NOW - timedelta(days=days)).strftime("%Y-%m-%d")
    out = run(f'gh issue list -R {repo} --state all --search "created:>={cutoff}" --limit 20 --json number,title,state,createdAt')
    try: return json.loads(out)
    except: return []

def generate():
    repos = get_repos()
    digest = {
        "date": TODAY,
        "repos_count": len(repos),
        "stale_issues": [],
        "stale_prs": [],
        "ci_failures": [],
        "recent_activity": [],
        "repos": repos
    }

    for repo in repos:
        for issue in get_stale_issues(repo):
            digest["stale_issues"].append({"repo": repo, "number": issue["number"], "title": issue["title"]})
        for pr in get_stale_prs(repo):
            digest["stale_prs"].append({"repo": repo, "number": pr["number"], "title": pr["title"]})
        ci = get_ci_status(repo)
        if ci == "failure":
            digest["ci_failures"].append(repo)
        for issue in get_recent_issues(repo):
            digest["recent_activity"].append({"repo": repo, **issue})

    return digest

def format_text(d):
    lines = [f"🌅 POKE LABS DAILY DIGEST — {d['date']}", f"📊 REPOS: {d['repos_count']} total", ""]

    lines.append(f"🔴 Stale Issues (>30d): {len(d['stale_issues'])}")
    for i in d['stale_issues'][:10]:
        lines.append(f"   • {i['repo']}#{i['number']} — {i['title']}")

    lines.append(f"\n🟡 Stale PRs (>7d): {len(d['stale_prs'])}")
    for p in d['stale_prs'][:10]:
        lines.append(f"   • {p['repo']}#{p['number']} — {p['title']}")

    lines.append(f"\n❌ CI Failures: {len(d['ci_failures'])}")
    for r in d['ci_failures']:
        lines.append(f"   • {r}")

    lines.append(f"\n📬 Recent Activity (7d): {len(d['recent_activity'])}")
    for a in d['recent_activity'][:15]:
        icon = "🆕" if a['state'] == 'open' else "✅"
        lines.append(f"   {icon} {a['repo']}#{a['number']} — {a['title']}")

    lines.append(f"\n🫧 Generated by Poke · {d['date']}")
    return "\n".join(lines)

if __name__ == "__main__":
    args = sys.argv[1:]
    digest = generate()
    if "--json" in args:
        print(json.dumps(digest, indent=2))
    else:
        text = format_text(digest)
        if "--output" in args:
            idx = args.index("--output")
            if idx + 1 < len(args):
                with open(args[idx + 1], 'w') as f:
                    f.write(text)
                print(f"Written to {args[idx + 1]}")
        else:
            print(text)
